### ISSUE TITLE
Input handling along the lines of re-frame example

### ISSUE THREAD

**Issue by egli** [sbsdev/daisyproducer2#65]
The re-frame examples contain some [neat code for general input field handling](https://github.com/day8/re-frame/blob/master/examples/todomvc/src/todomvc/views.cljs#L7). See if [our input handling code](https://github.com/sbsdev/daisyproducer2/blob/main/src/cljs/daisyproducer2/words/input_fields.cljs#L21) uses the same strategy and adapt if needed.

**Comment by plexus** [comment]
Creating some higher level components is always a good idea, you probably want to build up a bit of a "form component library" of individual bits that you can reuse. This can also help with consistent styling, consistent error handling, etc.

**Comment by egli** [comment]
Two things are interesting about the [examples above](https://github.com/day8/re-frame/blob/master/examples/todomvc/src/todomvc/views.cljs#L7):
1. the value of the field is kept locally to the field, i.e. it is not part of the application state. There is a closure that contains a reagent atom that keeps the value. Then the on-change callback just does a `reset!` of this value. The application state is only updated on blur or on pressing RET. This is an interesting idea and keeps the number of events much lower than in our implementation where a dispatch is triggered for each key press.
2. the render function takes a `props` argument that lets the user of the component pass in additional key/value pairs. In the example this is used to set the class attribute, etc. This gives a lot of flexibility.

**Comment by egli** [comment]
The first idea has now been implemented in [input_fields.cljs](https://github.com/sbsdev/daisyproducer2/blob/ad92b1f28955b54e10c91eb4fcbffd9cef76e0d1/src/cljs/daisyproducer2/words/input_fields.cljs#L28).
