### ISSUE TITLE
Fehlende Bestätigung bei Direkteingabe von Trennungen

### ISSUE THREAD

**Issue by mixa72** [sbsdev/daisyproducer2#78]
Nachdem man ein Wort ins Feld "Wort" eingetragen und dessen Trennung in "Korrigierte Trennung" korrigiert hat (screenshot_1_eingabe.png), bewirkt der "Speichern"-Button den erwünschten Insert in die DB, aber auf der Seite erscheint - statt einer Bestätigung - etwas vorschnell "Die Trennung ist schon definiert. Bitte benutzen Sie 'Editieren' um sie zu ändern" (screenshot_2_nach_eingabe.png).

![screenshot_1_eingabe](https://user-images.githubusercontent.com/1667959/112636236-16b45b80-8e3d-11eb-9fe6-59bbdbb26357.png)

![screenshot_2_nach_eingabe](https://user-images.githubusercontent.com/1667959/112636240-1916b580-8e3d-11eb-9c2b-281acf627839.png)

**Comment by egli** [comment]
Ah, yes, I see. As far as I know there is a confirmation that the saving happens. It is probably just very short: There should be a spinner on the save button.

I looked at the old system. After you save the word field is blank and hence you will not get the warning. Maybe we should do the same here.

**Comment by egli** [comment]
Fixed in b1fd662542b33f55e6a1e26b8b23d297f781bfe0
