### ISSUE TITLE
Refresh input field after save event

### ISSUE THREAD

**Issue by egli** [sbsdev/daisyproducer2#81]
Currently input fields have component local state mainly to facilitate a simple undo when pressing `ESC`. They keep the initial value of the field and reset the actual value to it when escape is pressed.

They also use this component local state [`initial-value`](https://github.com/sbsdev/daisyproducer2/blob/main/src/cljs/daisyproducer2/words/input_fields.cljs#L27) to give the input field a class: When the actual value is different that the initial value the input [field gets the "is-warning" class](https://github.com/sbsdev/daisyproducer2/blob/main/src/cljs/daisyproducer2/words/input_fields.cljs#L35) as an indication that a value was changed.

However when saving the value the component local state is not refreshed. The initial value should be reset to the newly saved value.

How can the component local state be changed? Presumably I'd have to drop the component and re-create it with the new initial value, but how?

**Comment by plexus** [comment]
Seems like you are actually closing over the value in your inner function and in your `save!` function, you'll have to change that to an atom so you can update it later on.

Something like this (untested), I've marked the lines that I've changed.

```clj
(defn input-field [page id field-id validator]
  (let [initial-value (reagent/atom @(rf/subscribe [::word-field page id field-id])) ;; <--- wrapped it in an atom
        get-value (fn [e] (-> e .-target .-value))
        reset! #(rf/dispatch [::set-word-field page id field-id @initial-value])
        save! #(do
                 (rf/dispatch [::set-word-field page id field-id %])
                 (reset! initial-value %))] ;; <---- reset on save
    (fn []
      (let [value @(rf/subscribe [::word-field page id field-id])
            valid? (validator value)
            changed? (not= @initial-value value) ;; <------ make sure to deref!
            klass (list (cond (not valid?) "is-danger"
                              changed? "is-warning")
                        ;; braille fields should be in mono space
                        (when (#{:contracted :uncontracted} field-id) "braille"))]
        [:div.field
         [:input.input {:type "text"
                        :aria-label (tr [field-id])
                        :class klass
                        :value value
                        :on-change #(save! (get-value %))
                        :on-key-down #(when (= (.-which %) 27) (reset!))}]
         (when-not valid?
           [:p.help.is-danger (tr [:input-not-valid])])]))))
```

**Comment by egli** [comment]
This is a bit more complicated than I had anticipated:

The current code which keeps the initial state as component local state works fine for components which are disposed once they are saved, such as unknown words or confirmed words

However for components which remain on the page after a save to the external server this doesn't work. As the initial value is local to the component it cannot be reset from outside. In theory the initial value should be local state to the form that contains the input fields and the submit button, so that the submit button could reset the initial state once the word has been persisted to the server.

There is also the [re-frame undo interceptor](https://github.com/Day8/re-frame-undo) which stores previous states of the app-db. However this has other problems as we do really want undo, just reset to the initial state.

**Comment by egli** [comment]
From the commit message:

> The issue is solved by assigning a new key to saved words so that component local state is refreshed

>The input fields of the words have component local state such as initial value. This is used for a simple undo mechanism. Now this local state should be invalidated when the word is actually saved (as we have a new initial value now). Since this component local state is implemented using a closure it cannot be changed fom outside. We would either have to implement the local state globally so that it could be changed from a save or the component would have to be recreated with
the new initial value.

>We choose option two by just assigning a new key to the word which essentially forces react to create a new component which will have a now closure with the right initial values.
